### ISSUE TITLE
feat: multiple images for items and users

### ISSUE THREAD

**Issue by rmaree** [shareish/shareish#20]
In front-end should be possible to add multiple images for items and profile.
Use of “Image carousel” https://buefy.org/documentation/carousel/
Function is available in backend

**Comment by banneux-florent** [comment]
Multiple images for items with predictions on /add-item works fine since commit [db6ddc7](https://github.com/shareish/shareish/commit/db6ddc7a75b58f9a9e5478be293b5b4ca9eba649) on branch [feat/multiple-images](https://github.com/shareish/shareish/compare/main...feature/multiple-images).

Users in progress.

**Comment by banneux-florent** [comment]
Multiple images for users is now also supported since merge of branch feat/multiple-images, on commit [9ba02bf](https://github.com/shareish/shareish/commit/9ba02bfb9069a119ba73bbca95ef8e76c1d3babb).
