### ISSUE TITLE
feat: close/unclose conversation in front-end

### ISSUE THREAD

**Issue by rmaree** [shareish/shareish#71]
add a button to close/unclose a conversation in the front-end conversation list

**Comment by banneux-florent** [comment]
Who could close and open the conversation? If only the author, the actual database structure is good, because the conversation itself contains a is_closed field and we could make it only editable by the owner. But if both parties could close the conversation, we need to store who closes it too to prevent the other person to re-open it later on. And if we store it, where/what would be the best?

**Comment by banneux-florent** [comment]
Button added on the top right corner of the conversation. Both users can close it and it can only be opened back by the one who closed it.

Be aware that this commit will open back any conversations that would have been closed previously.As the option wasn't available to the users before, they should all be open by default but, just to be sure.
