### ISSUE TITLE
feat: public resources are dynamic, implement a mechanism for comments/notes/notifications

### ISSUE THREAD

**Issue by rmaree** [shareish/shareish#84]
Public resources are in general dynamic e.g. a food sharing fridge can be broken / empty / dirty / ... ; a public bookcase might be empty/full/broken; etc.

For the moment we only allow to visualize or edit the OpenStreetMap tags that does not allow to encode this dynamic character, but if we had some kind of additional information around these it could foster community activity.

We might think about a table in our data model that allows to encode reviews/comments/status related to these a bit similarly than FallingFruit allows to add review/status of a plant (like when the fruit is good to eat or still in flower stage); or similarly than what the LA Community fridge are doing using the concept of "check-in": https://www.lacommunityfridges.com/ --> https://bit.ly/lacf-32

- Do we need a specific table for each public resource, or can we use generic fields such as "status" / "notes" ?

- Should people receive notifications when there is a new status/comment for a public resource ? Or should we only send notifications if a request/gift is created ?

- Should we then allow Shareish items to be linked to a public resources (e.g; if a specific fridge is said to be dirty a request to clean) ?

**Comment by banneux-florent** [comment]
About status, if implemented, I would go for a list of status that can match some of the public resources (broken could be affected to X, Y but not Z, full could be affected to Y but not X and Z, and so on). But what about users that want to do bad on the website? How to verify the status update? A Twitter "Community Notes"-like system of up-votes/down-votes to know if it can be validated? How does Wikipedia handle that too? Must be though more deeply maybe..

Notes on the other hands are not affecting other users directly as they are linked to users posting them so less trust in those because they are personal. Would be easier to implement.

Notifications? Yes, if it's correctly verified as I mentioned, but only if the settings are there to prevent unwanted notifications. The subscription system would fit perfectly there. I'm not a reader, I don't subscribe to the public bookcases. I know a specific tree somewhere and I'm waiting for its status to update, I subscribe! etc. Could be done with the current settings page but would be less precise. Maybe I don't want to be notified from all tree that i don't like, or all bookcases that are not on my usual travels/locations etc.

Link posts to public resources, a possibility. How about a status "dirty" that creates a post but that turns to "clean" later on? Automatically deletes the previous post? Who would be the author?

Overall, I think the platform should keep a strong identify that gravitates around users, their needs, their content, their competences, and not spread too much at first, but that's only my opinion. I'm just scared of a Facebook-like where we loose easy usage and the initial problem solving ahah.

**Comment by rmaree** [comment]
We definitely have to evaluate these designs with users at some point. 
I'm thinking about a basic first implementation. To be in line with other notifications, 
I think the combination of distance (kilometers) and frequency (instantly/daily/weekly/monthly) digest for public resources (like it is in fact done since commit 7ce064d) offers a first acceptable implementation. 
Then we could think about sub-categories of notifications that would allow for example: i want to be notified weekly about new/modifications of "food sharing" public resouces but never about "bookcases". That's the same for items/Events where people might be notified only for certain categories (e.g. "do-it-yourself" events).
Regarding the platform identity, we are trying to make a community aware of the different solidarity practices in the neighbourdhood and to ease active participation of people, so it includes awareness of public resources and requests related to them (e.g. a fridge need to be fixed/cleaned). If the user has to subscribe to each public resource, they might miss some public resources activities / requests. 
While writing, I realize that we already have requests+notifications, so if e.g. a public free fridge is dirty, one might simply create a request about it with a description, and public comments are there to discuss the issue. We might ease the creation of a request when someone click on the public resource in its popup add a link to "create new request (or a donation if someone wants to say e.g. they put new books in a bookcase)" where we prefill e.g. the category, address, and maybe a text template in the description. One option could be to have add an Item field that would be automatically filled with the OSM nodeid if we need to later filter/sort requests based on public resources but I'm not even sure it is necessary for a first basic implementation and this might be confusing for users willing to create a request not related to a public resource.
