### ISSUE TITLE
fix: reverse reference address not working anymore

### ISSUE THREAD

**Issue by rmaree** [shareish/shareish#92]
The api/v1/address/reverse of the reference address is not working in some cases since commit 1c339f6ba63b16b47fcd11ecd372c317c7be034a (use of gps coordinates) whatever the address is used. 
To test: on production site, either use the reference button on the map, or go to account settings, set a new address in reference address, save (it seems to work), then refresh the page.
"Couldn't find location."
400 Bad Request

**Comment by banneux-florent** [comment]
Should be fixed. Give it a try and call again if I ever forgot something.

---

I also fixed the location filter from /items as I saw it was broken. When we were selecting "Don't use geolocation" and typing an address, it didn't do anything. The functions that were previously in `frontend/src/views/TheItemsView.vue` were left there and not moved to `frontend/src/components/ItemsFilters.vue` so the filter couldn't call the API to retrieve the correct address etc.

Added minor update there too where you now can select a distance range when using this "Don't use geolocation" option (wasn't the case before, I don't know why?) + made the address field disabled when using geolocation or ref location (as you shouldn't be able to update those to be consistent in user experience).

I'll add a new issue tho, because a great way to make it possible would be to change the "philosophy" of that location filter. It would look like that: only 2 buttons (geolocation and ref location) in **click mode** instead of **selection mode**, 1 label "Address:" instead of "Or enter an address:" and the address field always never disabled. That way, the address filled by the buttons could be edited without being misinterpreted.

Lot of explanations but as I can't knock on your door anymore I give all the details in my comments ;)
